### ISSUE TITLE
There appears to be no way to control the normalisation.

### ISSUE THREAD

**Issue by iandobbie** [DiamondLightSource/StitchM#1]
I have a pure fluorescence mosaic that I want to stitch. It works fine but the normalisation is totally broken. All the regions with any fluorescence are totally saturated after normalisation.  I suggest you add a flag to turn off normalisation.

**Comment by iandobbie** [comment]
On a related note unstitched|_image.py has the following code

 self.exposures = location_array[:, 2]

This value is the Z position of the image, nothing to do with exposure times. I think this might be killing my attempted mosaic building as I am at Z position 20,000.

**Comment by iandobbie** [comment]
Added a no-normalisation flag to turn off normalisation developing in branch https://github.com/iandobbie/StitchM/tree/normalise-flag not properly tested yet.

**Comment by iandobbie** [comment]
> On a related note unstitched|_image.py has the following code
> 
> self.exposures = location_array[:, 2]
> 
> This value is the Z position of the image, nothing to do with exposure times. I think this might be killing my attempted mosaic building as I am at Z position 20,000.

I have opened a new issue #2 on this

**Comment by iandobbie** [comment]
I believe my new branch allows stitching without normalisation. 

One outstanding issue is that is creates a new argument "-n" or "--no-normalisation" that is a boolean and requires an additional parameter but whatever that parameter is the boolean is judge to be true.

**Comment by thomasmfish** [comment]
Normalise off branch seems good to me (other than a few stylistic things that I might change for consistency), so feel free to submit a PR. Hopefully I've set the mirroring up correctly that your PR will be copied over

**Comment by thomasmfish** [comment]
I will add that this was never meant for fluorescence mosaics (I didn't know this was something anyone wanted) but it sounds like a useful addition!

**Comment by iandobbie** [comment]
Please do feel free to clear up any issues, especially the weird inconsistency in the arg parsing. I couldn't work out how to just make it a flag. 

I do have a couple of other question though, 

1) why do unmapped pixels end up white? Can we make them black, at least in the unnormalised version. 
2) might it be possible to enable multiple mosaics to be merged into a single multi-channel tif? I just spent 2 days taking then merging together a 3 colour fl mosaic for our simulation mode. Here is cropped and scaled by 10x in each direction image of it. 
![merged-zaber-rgb-scaled](https://user-images.githubusercontent.com/5451909/106882772-0f8f8d80-66d7-11eb-983b-1fd08085fee0.jpg)

**Comment by thomasmfish** [comment]
> Please do feel free to clear up any issues, especially the weird inconsistency in the arg parsing. I couldn't work out how to just make it a flag.

Okay!

> I do have a couple of other question though,
> 
> 1. why do unmapped pixels end up white? Can we make them black, at least in the unnormalised version.

The unmapped pixels are white so that I can safely reserve the top pixel value as a mask. The idea behind this is it can be easily masked out when using it for alignment or whatever. You should be able to replace that top pixel value with whatever you'd like.

> 2. might it be possible to enable multiple mosaics to be merged into a single multi-channel tif? I just spent 2 days taking then merging together a 3 colour fl mosaic for our simulation mode. Here is cropped and scaled by 10x in each direction image of it.

Sure, it's possible. That's a bit beyond the scope of this for now though... Have you tried merging them in eC-CLEM? I've embedded the centre coordinates of the stitched mosaic in the metadata. While I have very little experience with eC-CLEM, I know it reads OME metadata and I'm thinking that it might be able to align the images based on the metadata coordinates...

Unfortunately, I'm now probably not going to get a chance to look into this this week, as some more urgent things have come up with regards to our TXM automation. Sorry!

**Comment by iandobbie** [comment]
> > 1. why do unmapped pixels end up white? Can we make them black, at least in the unnormalised version.
> 
> The unmapped pixels are white so that I can safely reserve the top pixel value as a mask. The idea behind this is it can be easily masked out when using it for alignment or whatever. You should be able to replace that top pixel value with whatever you'd like.

I changed the code to return 0 if the normalisation is turned off. 

> > 1. might it be possible to enable multiple mosaics to be merged into a single multi-channel tif? I just spent 2 days taking then merging together a 3 colour fl mosaic for our simulation mode. Here is cropped and scaled by 10x in each direction image of it.
> 
> Sure, it's possible. That's a bit beyond the scope of this for now though... Have you tried merging them in eC-CLEM? I've embedded the centre coordinates of the stitched mosaic in the metadata. While I have very little experience with eC-CLEM, I know it reads OME metadata and I'm thinking that it might be able to align the images based on the metadata coordinates...

Ah I didn't know that, it would probably have made life easier. I actually used imageJ and effectively located a couple of features and merged that. 

I might try to add the multi channel option but I'll have a think. I might not both as we now have this 45kx45k 3 colour image so I probably don't have to do it again any time soon. 

> 
> Unfortunately, I'm now probably not going to get a chance to look into this this week, as some more urgent things have come up with regards to our TXM automation. Sorry!

No rush. Just thought I should contribute the code back, especially as I am likely to be using it more.

**Comment by thomasmfish** [comment]
There are two aspects of normalisation that I am not sure what is best for:

* Exposure correction: compensate for different exposures for each image using the min/max values given in the text file.
* Rescaling to fit dtype: rescale the overall image to fill the whole range of uint16.

I'd assume you'd still want the second one, otherwise images may appear overly dark or you may have issues with values overflowing\*. However, I could alternatively just put a method in that would limit values (e.g. `if value > max: value = max`) to the range of the dtype if that'd be better?

\* Maybe what was happening in your divide by zero example?

**Comment by thomasmfish** [comment]
Hi @iandobbie I've copied your branch this repository so I can push to it. As it stands I've included the code to do either method of handling the dtypes of non-normalised images. Does this look okay?

I haven't tried the divide by zero issue yet.

Upate: I can't replicate the divide by zero issue with the files you sent, so I suspect it's been fixed by the other changes.

**Comment by iandobbie** [comment]
> * Exposure correction: compensate for different exposures for each image using the min/max values given in the text file.
> * Rescaling to fit dtype: rescale the overall image to fill the whole range of uint16.
> 
> I'd assume you'd still want the second one, otherwise images may appear overly dark or you may have issues with values overflowing*. However, I could alternatively just put a method in that would limit values (e.g. `if value > max: value = max`) to the range of the dtype if that'd be better?

Generally I would do neither of these for fluorescence images. 

1) The min max levels in fluorescence depend entirely upon the local dye concentrations, so rescaling to this means each image is scaled arbitrarily. 

2) Although the image may look dark if you dont stretch the contrast, keeping real output values is massively advantageous for fluorescence imaging. As soon a you stretch the data to fill the dtype you loose any possibility of comparing across images, or between imaging systems. Although not directly measured in photons, the original camera counts are directly relatable to photon count levels. If you later look at the images, the noise levels look horrendous if you stretch to fill the dtype. 

So no, I just want to stitch the images as is, and I added code to make "blank" areas 0, rather than dtype max value as well.

**Comment by thomasmfish** [comment]
Okay, this is what I've done - give it a go if you'd like

**Comment by iandobbie** [comment]
Ok will do.

**Comment by iandobbie** [comment]
Had a quick try and it is failing to find the command line functions. Maybe something to do with moving the files around. Just getting lunch then I’ll have more of a look

Ian

Sent from my iPhone

On 12 Feb 2021, at 12:11, Thomas Fish <notifications@github.com> wrote:

﻿

Okay, this is what I've done - give it a go if you'd like

**Comment by thomasmfish** [comment]
I'm not having any issues with that but it will require reinstallation if you are using `python -m pip -e .` to install it, as setup.py has changed

**Comment by iandobbie** [comment]
Weird I get:

    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'stitch_m.scripts.commandline'

**Comment by thomasmfish** [comment]
I'll try on a different computer

**Comment by iandobbie** [comment]
So I have stitch_m/csripts which doesnt have commandline.py in it but also src/stitch_m/scripts which does have the relevant code in it.

**Comment by thomasmfish** [comment]
> 
> 
> So I have stitch_m/csripts which doesnt have commandline.py in it but also src/stitch_m/scripts which does have the relevant code in it.

stitch_m/scripts shouldn't be there any more... What happens if you delete that (it's not in the repo any more)?

**Comment by thomasmfish** [comment]
I had to delete the original branch and pull it again to avoid conflicts due to my rebase

**Comment by iandobbie** [comment]
I just tried deleting the ./stitch_m and now get ModuleNotFoundError: No module named 'stitch_m' so its like it isnt findsing the src/stitch_m I will try to nuke it all and start again.

**Comment by thomasmfish** [comment]
I just tried it on another PC without issue, so I think nuking it is the best option

**Comment by iandobbie** [comment]
Nope, uninstalled it all. Nuked the dir, recloned from github, reinstalled.

ModuleNotFoundError: No module named 'stitch_m'

I think there must be a path error in the setup.py

**Comment by thomasmfish** [comment]
are your pip and setuptools up to date? I'm using
```
pip                     20.1.1
setuptools              49.1.0
```

**Comment by iandobbie** [comment]
pip 21.0.1 setuptools '49.2.1' python 3.8.6 on a mac

**Comment by thomasmfish** [comment]
A mac is the one thing I can't easily test on... I've tested on Windows and Linux without issue though, both from your repo and this one

**Comment by thomasmfish** [comment]
```
(b24) C:\Users\rky95813\Documents\StitchM>python -m pip install .
Processing c:\users\rky95813\documents\stitchm
Requirement already satisfied: tifffile in c:\users\rky95813\miniconda3\envs\b24\lib\site-packages (from StitchM==1.1.0) (2021.2.1)
Requirement already satisfied: mrcfile in c:\users\rky95813\miniconda3\envs\b24\lib\site-packages (from StitchM==1.1.0) (1.2.0)                                                                                                                 Requirement already satisfied: numpy in c:\users\rky95813\miniconda3\envs\b24\lib\site-packages (from StitchM==1.1.0) (1.20.1)
Requirement already satisfied: omexml-dls in c:\users\rky95813\miniconda3\envs\b24\lib\site-packages (from StitchM==1.1.0) (1.0.3)
Requirement already satisfied: pywin32 in c:\users\rky95813\miniconda3\envs\b24\lib\site-packages (from StitchM==1.1.0) (300)                                                                                                                   Requirement already satisfied: future in c:\users\rky95813\miniconda3\envs\b24\lib\site-packages (from omexml-dls->StitchM==1.1.0) (0.18.2)
Building wheels for collected packages: StitchM
Building wheel for StitchM (setup.py) ... done
Created wheel for StitchM: filename=StitchM-1.1.0-py3-none-any.whl size=19542 sha256=ec0b3271f1059df3b842c82be364c1ac1f1f7e21942fc87ba2e6a3af2ebde261
Stored in directory: C:\Users\rky95813\AppData\Local\Temp\pip-ephem-wheel-cache-qwphkdoe\wheels\89\b4
\93\8a4926691c9e5911f5d971c7ade9b9bae37e125dfe6ddeca90
Successfully built StitchM
Installing collected packages: StitchM
Successfully installed StitchM-1.1.0
(b24) C:\Users\rky95813\Documents\StitchM>StitchM -v
StitchM 1.1.0
```

Why, Windows, do you not copy newlines from the command line!?

**Comment by thomasmfish** [comment]
> 
> 
> Nope, uninstalled it all. Nuked the dir, recloned from github, reinstalled.
> 
> ModuleNotFoundError: No module named 'stitch_m'
> 
> I think there must be a path error in the setup.py

Are you sure you're not in master? There is currently an issue with master, as I didn't update the setup.py correctly when changing the structure, but that's fixed in this branch (I should really fix it separately)

Master should be fixed now (on this repo)

**Comment by iandobbie** [comment]
Of course I'm in  master. I never thought there was another branch to checkout. Sorry

**Comment by iandobbie** [comment]
Sorry I totally assumed you had pulled it into master. The branch appears to work fine.

**Comment by thomasmfish** [comment]
Ah, sorry, I just coped across your branch rather than merging it and didn't make that clear enough. Glad it's working!
