### ISSUE TITLE
Exposure value incorrectly read from source mrc file. 

### ISSUE THREAD

**Issue by iandobbie** [DiamondLightSource/StitchM#2]
stitched_image.py has the following code

self.exposures = location_array[:, 2]

this value is actually the Z position of the data, not related to the exposure time at all.

**Comment by thomasmfish** [comment]
Ah, that isn't good. Thankfully that value is only used in the metadata, so won't be hurting the normalisation. Is there an exposure time reported in that file at all?

**Comment by thomasmfish** [comment]
It seems like the answer is no, having had a look. The value I'm most curious about is the final value that seems to be always 0... What does that mean?

**Comment by iandobbie** [comment]
Code which write the text file is:

       for tile in self.tiles:
            width = max(width, tile.textureData.shape[0])
            height = max(height, tile.textureData.shape[1])
            # We do this by a series of extensions since some of these lists
            # may be Numpy arrays, which don't do array extension when you
            # "add" them.
            values = []
            values.extend(tile.pos)
            values.extend(tile.size)
            values.extend(tile.textureData.shape)
            values.extend(tile.histogramScale)
            values.append(tile.layer)
            values = map(str, values)
            handle.write(','.join(values) + '\n')
        handle.close()

this is from cockpit/cockpit/gui/mosaic/canvas.py in function saveTiles

Dont know if this will actually be any help, but my reading of this is no info about exposure time.

**Comment by thomasmfish** [comment]
I've removed exposure from the metadata. One thing here that I missed before is `tile.layer` - what does this mean/how is this used?

**Comment by iandobbie** [comment]
Thomas Fish <notifications@github.com> writes:

> I've removed exposure from the metadata. One thing here that I missed before is tile.layer -
> what does this mean/how is this used?

I think it was originally included to enable different layers in the
mosaic which could be individually turned on and off. I am actually
exploring it at the moment to try and get colour into the mosaics.

The current code just sets it to 1 and leaves it at that. We should
probably link it to the camera, emission filter and light source used
but it currently isn't used.


Ian

**Comment by thomasmfish** [comment]
> I think it was originally included to enable different layers in the mosaic which could be individually turned on and off. I am actually exploring it at the moment to try and get colour into the mosaics. The current code just sets it to 1 and leaves it at that. We should probably link it to the camera, emission filter and light source used but it currently isn't used. Ian

That would be excellent! Please let me know if/when that changes and I'll change StitchM to split by channel
