### ISSUE TITLE
Some data can generate a divide by zero.

### ISSUE THREAD

**Issue by iandobbie** [DiamondLightSource/StitchM#3]
I have a data set that generates the following error.

/Users/ian/src/StitchM/stitch_m/image_normaliser.py:66: RuntimeWarning: divide by zero encountered in true_divide
  rescaled_images = corrected_images * (new_max / corrected_max)

presumably the corrected_max is zero. I can provide the data but it is unfortunately a multi GB file.

**Comment by thomasmfish** [comment]
Hi Ian! I didn't get alerted to your issues, sorry, we use GitLab now, so this is just a mirror of that. I'll have a look at your issues & branch now!

**Comment by iandobbie** [comment]
Having a look do you need an account on gitlab to access it?

**Comment by thomasmfish** [comment]
To access it you'd have to have a Diamond GitLab account but I've set up the mirroring to work in both directions now, so changes here should get reflected there

**Comment by iandobbie** [comment]
Ok. I’ll keep my discussion and changes here for the moment then.

**Comment by thomasmfish** [comment]
Closing this as this seems to be fixed by the no-normalisation tag
