### ISSUE TITLE
Latest version dies with error

### ISSUE THREAD

**Issue by iandobbie** [DiamondLightSource/StitchM#6]
StitchM -m green-60x-mosaic.txt
WARNING:root:Cannot find path /Users/ian/Documents/projects/Zaber/mosaic/C:\MUI_DATA\bioc0882\green-60x-mosaic.mrc
WARNING:root:mrc file with the same name in the current directory will be used
WARNING:root:Cannot find path /Users/ian/Documents/projects/Zaber/mosaic/C:\MUI_DATA\bioc0882\green-60x-mosaic.mrc
WARNING:root:mrc file with the same name in the current directory will be used
/Users/ian/Library/Python/3.9/lib/python/site-packages/mrcfile/mrcinterpreter.py:209: RuntimeWarning: Map ID string not found - not an MRC file, or file is corrupt
  warnings.warn(msg, RuntimeWarning)
/Users/ian/Library/Python/3.9/lib/python/site-packages/mrcfile/mrcinterpreter.py:219: RuntimeWarning: Unrecognised machine stamp: 0x00 0x00 0x00 0x00
  warnings.warn(str(err), RuntimeWarning)
ERROR:root:Error has occurred while stitching or saving mosaic. Please see traceback for more info.
Traceback (most recent call last):
  File "/Users/ian/Library/Python/3.9/lib/python/site-packages/stitch_m/run.py", line 55, in _stitch
    metadata_creator = MetadataMaker(tiff_filename, unstitched, stitcher.get_brightfield_list())
TypeError: __init__() missing 1 required positional argument: 'datatype'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/ian/Library/Python/3.9/lib/python/site-packages/stitch_m/run.py", line 94, in main_run
    mosaic, metadata, tiff_file = _stitch(config, mosaic, markers, normalise)
  File "/Users/ian/Library/Python/3.9/lib/python/site-packages/stitch_m/run.py", line 65, in _stitch
    arg_string = ", ".join((str(mosaic or None), str(markers or None), str(normalise)))
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
Processing failed! Press enter to exit

**Comment by thomasmfish** [comment]
Fixed with 1.2.0
